package model;

// Generated Dec 19, 2012 8:13:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity")
public class Activity implements java.io.Serializable {

	private Integer idactivity;
	private Employee employee;
	private Project project;
	private Integer charge;
	private Date day;

	public Activity() {
	}

	public Activity(Employee employee, Project project) {
		this.employee = employee;
		this.project = project;
	}

	public Activity(Employee employee, Project project, Integer charge, Date day) {
		this.employee = employee;
		this.project = project;
		this.charge = charge;
		this.day = day;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idactivity", unique = true, nullable = false)
	public Integer getIdactivity() {
		return this.idactivity;
	}

	public void setIdactivity(Integer idactivity) {
		this.idactivity = idactivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_idemployee", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_idproject", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "charge")
	public Integer getCharge() {
		return this.charge;
	}

	public void setCharge(Integer charge) {
		this.charge = charge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "day", length = 10)
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

}
