package model;

// Generated 14 janv. 2013 14:20:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivityId generated by hbm2java
 */
@Embeddable
public class ActivityId implements java.io.Serializable {

	private int idactivity;
	private int employeeIdemployee;
	private int projectIdproject;

	public ActivityId() {
	}

	public ActivityId(int idactivity, int employeeIdemployee,
			int projectIdproject) {
		this.idactivity = idactivity;
		this.employeeIdemployee = employeeIdemployee;
		this.projectIdproject = projectIdproject;
	}

	@Column(name = "idactivity", nullable = false)
	public int getIdactivity() {
		return this.idactivity;
	}

	public void setIdactivity(int idactivity) {
		this.idactivity = idactivity;
	}

	@Column(name = "employee_idemployee", nullable = false)
	public int getEmployeeIdemployee() {
		return this.employeeIdemployee;
	}

	public void setEmployeeIdemployee(int employeeIdemployee) {
		this.employeeIdemployee = employeeIdemployee;
	}

	@Column(name = "project_idproject", nullable = false)
	public int getProjectIdproject() {
		return this.projectIdproject;
	}

	public void setProjectIdproject(int projectIdproject) {
		this.projectIdproject = projectIdproject;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivityId))
			return false;
		ActivityId castOther = (ActivityId) other;

		return (this.getIdactivity() == castOther.getIdactivity())
				&& (this.getEmployeeIdemployee() == castOther
						.getEmployeeIdemployee())
				&& (this.getProjectIdproject() == castOther
						.getProjectIdproject());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdactivity();
		result = 37 * result + this.getEmployeeIdemployee();
		result = 37 * result + this.getProjectIdproject();
		return result;
	}

}
