package model;

<<<<<<< HEAD
// Generated 14 janv. 2013 16:54:08 by Hibernate Tools 3.4.0.CR1
=======
// Generated 14 janv. 2013 14:20:50 by Hibernate Tools 3.4.0.CR1
>>>>>>> branch 'master' of https://github.com/Meg4mi/GAC.git

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avancement generated by hbm2java
 */
@Entity
@Table(name = "avancement")
public class Avancement implements java.io.Serializable {

	private int idavancement;
	private Integer nbrHeures;
	private int employeeIdemployee;
	private int activityIdactivity;
	private Date dateEntry;

	public Avancement() {
	}

	public Avancement(int idavancement, int employeeIdemployee,
			int activityIdactivity) {
		this.idavancement = idavancement;
		this.employeeIdemployee = employeeIdemployee;
		this.activityIdactivity = activityIdactivity;
	}

	public Avancement(int idavancement, Integer nbrHeures,
			int employeeIdemployee, int activityIdactivity, Date dateEntry) {
		this.idavancement = idavancement;
		this.nbrHeures = nbrHeures;
		this.employeeIdemployee = employeeIdemployee;
		this.activityIdactivity = activityIdactivity;
		this.dateEntry = dateEntry;
	}

	@Id
	@Column(name = "idavancement", unique = true, nullable = false)
	public int getIdavancement() {
		return this.idavancement;
	}

	public void setIdavancement(int idavancement) {
		this.idavancement = idavancement;
	}

	@Column(name = "nbrHeures")
	public Integer getNbrHeures() {
		return this.nbrHeures;
	}

	public void setNbrHeures(Integer nbrHeures) {
		this.nbrHeures = nbrHeures;
	}

	@Column(name = "employee_idemployee", nullable = false)
	public int getEmployeeIdemployee() {
		return this.employeeIdemployee;
	}

	public void setEmployeeIdemployee(int employeeIdemployee) {
		this.employeeIdemployee = employeeIdemployee;
	}

	@Column(name = "activity_idactivity", nullable = false)
	public int getActivityIdactivity() {
		return this.activityIdactivity;
	}

	public void setActivityIdactivity(int activityIdactivity) {
		this.activityIdactivity = activityIdactivity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateEntry", length = 10)
	public Date getDateEntry() {
		return this.dateEntry;
	}

	public void setDateEntry(Date dateEntry) {
		this.dateEntry = dateEntry;
	}

}
