package model;

// Generated 14 janv. 2013 16:36:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RealmRole generated by hbm2java
 */
@Entity
@Table(name = "realm_role")
public class RealmRole implements java.io.Serializable {

	private RealmRoleId id;

	public RealmRole() {
	}

	public RealmRole(RealmRoleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)),
			@AttributeOverride(name = "roleName", column = @Column(name = "role_name", nullable = false, length = 45)) })
	public RealmRoleId getId() {
		return this.id;
	}

	public void setId(RealmRoleId id) {
		this.id = id;
	}

}
