package model;

// Generated Dec 19, 2012 8:13:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RealmUsers generated by hbm2java
 */
@Entity
@Table(name = "realm_users")
public class RealmUsers implements java.io.Serializable {

	private String userName;
	private String userPass;

	public RealmUsers() {
	}

	public RealmUsers(String userName) {
		this.userName = userName;
	}

	public RealmUsers(String userName, String userPass) {
		this.userName = userName;
		this.userPass = userPass;
	}

	@Id
	@Column(name = "user_name", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_pass")
	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

}
