package model;

// Generated 20 déc. 2012 10:08:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RealmUser generated by hbm2java
 */
@Entity
@Table(name = "realm_user")
public class RealmUser implements java.io.Serializable {

	private String username;
	private String password;

	public RealmUser() {
	}

	public RealmUser(String username) {
		this.username = username;
	}

	public RealmUser(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
